// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwd5cN9Qj7lMmKfjHkAVmAKlm2wKfx0FA',
    appId: '1:482837518599:web:563eb5b6f9f1d31e6acda2',
    messagingSenderId: '482837518599',
    projectId: 'boxcontroller-694ad',
    authDomain: 'boxcontroller-694ad.firebaseapp.com',
    storageBucket: 'boxcontroller-694ad.firebasestorage.app',
    measurementId: 'G-PLF8HL5R5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdMagcAmusoepUxhuTW6Ywa7_tawG1at0',
    appId: '1:482837518599:android:9f6c357ef6272fcf6acda2',
    messagingSenderId: '482837518599',
    projectId: 'boxcontroller-694ad',
    storageBucket: 'boxcontroller-694ad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX2cqa4MU9ly7N3SHZR1g6BZ7ghRstFzk',
    appId: '1:482837518599:ios:2739138da430d0c56acda2',
    messagingSenderId: '482837518599',
    projectId: 'boxcontroller-694ad',
    storageBucket: 'boxcontroller-694ad.firebasestorage.app',
    iosBundleId: 'com.example.boxController',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCX2cqa4MU9ly7N3SHZR1g6BZ7ghRstFzk',
    appId: '1:482837518599:ios:2739138da430d0c56acda2',
    messagingSenderId: '482837518599',
    projectId: 'boxcontroller-694ad',
    storageBucket: 'boxcontroller-694ad.firebasestorage.app',
    iosBundleId: 'com.example.boxController',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwd5cN9Qj7lMmKfjHkAVmAKlm2wKfx0FA',
    appId: '1:482837518599:web:a343906bc69e23bb6acda2',
    messagingSenderId: '482837518599',
    projectId: 'boxcontroller-694ad',
    authDomain: 'boxcontroller-694ad.firebaseapp.com',
    storageBucket: 'boxcontroller-694ad.firebasestorage.app',
    measurementId: 'G-K1S86CLZJR',
  );
}
